### ISSUE TITLE
`_addedScriptHashesCleanInterval` is not always cleared on `redis.quit()`

### ISSUE THREAD

**Issue by trentm** [luin/ioredis#1215]
Hi. I believe https://github.com/luin/ioredis/commit/3b22f8f89c3239fbbbc16da692651f6a35eca53a added a bug where the new `this._addedScriptHashesCleanInterval = setInterval(...)` (https://github.com/luin/ioredis/commit/3b22f8f89c3239fbbbc16da692651f6a35eca53a#diff-d3d9763dec19cf3dd977c437e0be3e6068b13161ee5a2b9b0bf225bddd2d83f8R188) isn't cleared via `clearInterval()` in all cases. This results in a dangling active handle that will hang a node process.

Here is a repro:

```js
var Redis = require('.'); // ioredis
var redis = new Redis();
redis.on('ready', function () {
    console.log('ready');
    redis.quit();
    console.log('done');
});
```

```
% node hang.js
ready
done
<hangs here>
```

or with ioredis debug output:

```
% DEBUG=ioredis:* node hang.js
  ioredis:redis status[localhost:6379]: [empty] -> connecting +0ms
  ioredis:redis status[127.0.0.1:6379]: connecting -> connect +6ms
  ioredis:redis write command[127.0.0.1:6379]: 0 -> info([]) +2ms
  ioredis:redis status[127.0.0.1:6379]: connect -> ready +4ms
ready
  ioredis:redis write command[127.0.0.1:6379]: 0 -> quit([]) +1ms
done
  ioredis:redis status[127.0.0.1:6379]: ready -> close +3ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[127.0.0.1:6379]: close -> end +1ms
<hangs here>
```

This does not happen if one uses `redis.disconnect()` instead of `redis.quit()`.

When calling `redis.quit()`, the closeHandler (in event_handler.ts) is called with `self.manuallyClosing == true` which does **not** call the  `clearInterval` added to `Redis.prototype.disconnect()`.

Some options I see (though I am not very familiar with ioredis, so I'm definitely happy to be overriden):

1. Add `this._addedScriptHashesCleanInterval.unref()` (https://nodejs.org/api/timers.html#timers_timeout_unref) to the `connect` method.  That'll prevent node from hanging, but *will* persist the setInterval after a program is presumably finished with the ioredis session.
2. Refactor the use of the `closeHandler` to explicitly call `clearInterval`.
3. Refactor access to `this._addedScriptHashes` so that it doesn't require a setInterval to clear it. E.g. perhaps something like https://github.com/isaacs/node-lru-cache using its `maxAge` option.

**Comment by AVVS** [comment]
@ShogunPanda could you take a stab at fixing this?

**Comment by ShogunPanda** [comment]
@AVVS Sure. Tomorrow (CET) I will take a look!

**Comment by ShogunPanda** [comment]
@AVVS Fixed in #1219 :)

**Comment by ejose19** [comment]
This error is still not fixed, here's a simple repro case:

```index.mjs```
```mjs index.mjs
import Redis from 'ioredis';

const redis = new Redis();

await new Promise((r) => setTimeout(r, 2000));

console.log('Sleep done');

await redis.quit();
```
don't start the redis server and run the script, notice how it's hanging on the ```quit()``` function.

Note: Last working version is ```4.17.3```
